version: '2.4'

services:
  couchbase:
    image: couchbase:6.0.2
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 8094:8094
      - 11210:11210
    healthcheck:
      test: ["CMD", "curl", "-f", "http://Administrator:Hermes159@localhost:8091/pools"]
      interval: 1s
      timeout: 3s
      retries: 60

  app:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      couchbase:
        condition: service_healthy